const github = 'https://github.com/RahulRachhoya';

export const projects = [
  {
    id: 'research-agent',
    repo: 'ai-sdk-research-agent',
    title: 'A research agent that remembers.',
    category: 'Agents & RAG',
    kind: 'Web application',
    description: 'A streaming research assistant with cited papers, persistent conversations, and memory that carries across chats.',
    stack: ['TypeScript', 'Next.js', 'Vercel AI SDK', 'Qdrant', 'MongoDB'],
    result: '300 / 300',
    resultLabel: 'BM25 token-ID matches with Python',
    github: `${github}/ai-sdk-research-agent`,
    evidence: `${github}/ai-sdk-research-agent/blob/main/docs/parity.json`,
    demo: 'https://ai-sdk-research-agent.vercel.app/',
    architecture: ['Next.js', 'Agent + tools', 'Hybrid search', 'MongoDB memory'],
    question: 'Can a Python research agent become a useful TypeScript application without losing retrieval quality?',
    implementation: 'Ported BM25 tokenization, stemming, hashing, and dense query embeddings to Node. The server owns chat history, injects saved memories, and records tokens, cost, and latency for every model step and tool call.',
    findings: [
      ['300 / 300', 'Queries with identical BM25 token IDs'],
      ['0.99999', 'Minimum dense-vector cosine similarity'],
      ['3.0 ms', 'Local dense-query p50 with node:http'],
    ],
    insight: 'The HTTP client mattered: the official Qdrant JS client took 60.9 ms versus 3.0 ms with node:http for local dense queries.',
    limit: 'These transport timings are from one Windows machine. Hybrid rankings can differ on tied scores. The public demo uses Groq; recorded agent benchmarks used Claude on AWS Bedrock. Search may take a moment to wake up.',
    build: 'Vercel hosts the app, Render runs embedding search, and Qdrant Cloud and MongoDB Atlas store retrieval data and conversations.',
  },
  {
    id: 'fine-tuning',
    repo: 'finetune-intent-lab',
    title: 'When does fine-tuning earn its keep?',
    category: 'Fine-tuning',
    kind: 'Reproducible experiment',
    description: 'Five approaches to one 77-class intent task, from a simple linear model to a QLoRA-tuned language model.',
    stack: ['QLoRA', 'PyTorch', 'Transformers', 'scikit-learn', 'MLflow'],
    result: '93.4%',
    resultLabel: 'Banking77 test accuracy',
    github: `${github}/finetune-intent-lab`,
    evidence: `${github}/finetune-intent-lab/blob/main/docs/results.json`,
    architecture: ['Banking77', 'Fixed split', 'QLoRA + baselines', 'MLflow evaluation'],
    question: 'When is training a small open model worth the effort compared with prompting or classic machine learning?',
    implementation: 'Fine-tuned Qwen2.5-1.5B-Instruct with 4-bit NF4 and rank-16 LoRA. Compared it with TF-IDF logistic regression, a PyTorch EmbeddingBag model, zero-shot Qwen, and prompted Claude. Tuning used a held-out validation split.',
    findings: [
      ['36.9 → 93.4%', 'Zero-shot to QLoRA test accuracy'],
      ['1.2%', 'Model parameters trained'],
      ['18 minutes', 'Training on a laptop GPU'],
    ],
    insight: 'The simple baseline stayed competitive: logistic regression scored 91.1%. On the same 300-query subset, QLoRA scored 91.0% and prompted Claude 83.7%.',
    limit: 'Local models used all 3,076 test queries; Claude used a 300-query sample. Batched local latency and sequential API latency are different workloads. This is one task and one seed, not a universal model ranking.',
    build: 'The repository includes the trained adapter through Git LFS, a model card, pinned dependencies, and exported MLflow results.',
  },
  {
    id: 'model-serving',
    repo: 'llm-serving-k8s',
    title: 'From trained adapter to served model.',
    category: 'Inference',
    kind: 'Local GPU benchmark',
    description: 'The same intent classifier, served with vLLM on Kubernetes and measured under concurrent requests.',
    stack: ['vLLM', 'Kubernetes', 'k3d', 'LoRA', 'Prometheus'],
    result: '185.5',
    resultLabel: 'requests / second at 32 concurrent requests',
    github: `${github}/llm-serving-k8s`,
    evidence: `${github}/llm-serving-k8s/blob/main/docs/results.json`,
    architecture: ['Qwen + adapter', 'vLLM', 'GPU Kubernetes', 'Load + metrics'],
    question: 'What changes when a fine-tuned model becomes an HTTP service, and where does serving time actually go?',
    implementation: 'Built a one-node k3d cluster on Docker Desktop and WSL2, passed the GPU through with the NVIDIA device plugin, and deployed vLLM with health probes. Measured concurrency, network paths, CUDA graph trade-offs, and restart downtime.',
    findings: [
      ['185.5 req/s', 'Peak at 32 in flight; p50 172 ms'],
      ['78 ms', 'p50 at one request in flight'],
      ['93.21%', 'Accuracy on 3,076 test queries'],
    ],
    insight: 'A restart cost five minutes, with about half spent capturing CUDA graphs. More concurrency stopped helping after 32 requests.',
    limit: 'One laptop GPU, one replica, and short classification outputs. Multi-GPU scaling and autoscaling are discussed, not tested. Served accuracy was 93.21% versus 93.43% during training-time evaluation.',
    build: 'Deployment manifests, the WSL2 GPU fix, the load generator, and Prometheus-derived timing breakdowns are all in the repository.',
  },
  {
    id: 'agent-memory',
    repo: 'agent-memory-lab',
    title: 'Better retrieval. Memory that lasts.',
    category: 'Agents & RAG',
    kind: 'Retrieval benchmark + agent',
    description: 'Qdrant versus pgvector on SciFact, followed by a LangGraph agent with durable memory and per-call telemetry.',
    stack: ['LangGraph', 'Qdrant', 'pgvector', 'MongoDB', 'AWS Bedrock'],
    result: '0.725',
    resultLabel: 'nDCG@10 with BM25 + dense retrieval',
    github: `${github}/agent-memory-lab`,
    evidence: `${github}/agent-memory-lab/blob/main/docs/results.json`,
    architecture: ['SciFact', 'BM25 + dense', 'RRF fusion', 'LangGraph + memory'],
    question: 'Does hybrid search help, and what does an agent need to remember useful context across sessions?',
    implementation: 'Benchmarked 300 claims over 5,183 abstracts with shared embeddings, matching fusion settings, and verified HNSW indexes. Added MongoDB checkpoints, long-term memory, and aggregation reports for a LangGraph agent.',
    findings: [
      ['0.725', 'Qdrant hybrid nDCG@10'],
      ['0.713', 'Dense nDCG@10 in both stores'],
      ['0.965', 'Hybrid Recall@100'],
    ],
    insight: 'Adding a weak retriever made results worse: Postgres built-in full-text search pulled its hybrid score down to 0.593. The tested reranker also reduced quality.',
    limit: 'One small corpus and one machine. Hybrid score ties introduce about ±0.004 variation. A five-turn agent demo demonstrates persistence and telemetry, not an answer-quality evaluation.',
    build: 'Docker Compose runs all three stores. Saved memories are injected into the prompt so the agent does not have to remember to call recall.',
  },
];
